# Generated by Django 5.0.3 on 2024-04-29 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.TextField(max_length=255, primary_key=True, serialize=False)),
                ('credit', models.IntegerField(default=4)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_major', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereqs', to='courses.course')),
                ('prereqs', models.ManyToManyField(related_name='required_by', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='MajorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=1)),
                ('courses', models.ManyToManyField(related_name='major_requirements', to='courses.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='courses.major')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.SmallIntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')])),
                ('credit', models.SmallIntegerField(default=0)),
                ('major', models.ManyToManyField(blank=True, to='courses.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_taken_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_courses', to='courses.student')),
            ],
        ),
    ]
