# Generated by Django 5.0.3 on 2024-04-08 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_major', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('begin_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('credit', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=255)),
                ('at_fall', models.BooleanField(default=True)),
                ('at_spring', models.BooleanField(default=True)),
                ('prereqs', models.ManyToManyField(blank=True, related_name='pre_req_of', to='courses.course')),
                ('majors', models.ManyToManyField(blank=True, related_name='courses', to='courses.major')),
                ('times', models.ManyToManyField(blank=True, related_name='courses', to='courses.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_id', models.SmallIntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')])),
                ('credit', models.SmallIntegerField()),
                ('major', models.ManyToManyField(blank=True, to='courses.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_taken_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(max_length=20)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
        ),
    ]
