# Generated by Django 5.0.3 on 2024-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_student_taken_course_studenttakencourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_id',
            field=models.SmallIntegerField(choices=[(0, 'preschool'), (1, 'freshman_1st'), (2, 'freshman_2nd'), (3, 'sophomore_1st'), (4, 'sophomore_2nd'), (5, 'junior_1st'), (6, 'junior_2nd'), (7, 'senior_1st'), (8, 'senior_2nd')]),
        ),
    ]
